insert into dim_position values (1, "Forward ");
insert into dim_position values (2, "Centre-Forward");
insert into dim_position values (3, "Defender ");
insert into dim_position values (4, "Right-Back");
insert into dim_position values (5, "Midfielder ");
insert into dim_position values (6, "Defensive Midfield");
insert into dim_position values (7, "Goalkeeper");
insert into dim_position values (8, "Right Midfield");
insert into dim_position values (9, "Left Winger");
insert into dim_position values (10, "Attacking Midfield");
insert into dim_position values (11, "Left-Back");
insert into dim_position values (12, "Centre-Back");
insert into dim_position values (13, "Right Winger");
insert into dim_position values (14, "Central Midfield");
insert into dim_position values (15, "Left");
insert into dim_position values (16, "NA");
insert into dim_position values (17, "Second Striker");
insert into dim_position values (18, "Left Midfield");
insert into dim_position values (19, "Centre");
insert into dim_position values (20, "Right");
insert into dim_position values (21, "Midfielder");
