insert into dim_agent values (1, "NA");
insert into dim_agent values (2, "Kögl & Partner GmbH");
insert into dim_agent values (3, "SportPlus Football ...");
insert into dim_agent values (4, "PRO FC");
insert into dim_agent values (5, "DC International ...");
insert into dim_agent values (6, "M-Soccermanagement");
insert into dim_agent values (7, "11WINS");
insert into dim_agent values (8, "LIAN SPORTS");
insert into dim_agent values (9, "GRASS IS GREEN");
insert into dim_agent values (10, "SportsTotal");
insert into dim_agent values (11, "Promoesport");
insert into dim_agent values (12, "act");
insert into dim_agent values (13, "Juanma López y ...");
insert into dim_agent values (14, "SEG");
insert into dim_agent values (15, "arena11 sports group");
insert into dim_agent values (16, "T21plus");
insert into dim_agent values (17, "Siebert & Backs");
insert into dim_agent values (18, "ROGON");
insert into dim_agent values (19, "Coaches & More GmbH");
insert into dim_agent values (20, "Daniel Van Buyten");
insert into dim_agent values (21, "ProSoccer");
insert into dim_agent values (22, "AL Eventos ...");
insert into dim_agent values (23, "PRO Profil GmbH");
insert into dim_agent values (24, "Rechtsanwalt Oliver ...");
insert into dim_agent values (25, "FSB – ...");
insert into dim_agent values (26, "feel soccer GmbH");
insert into dim_agent values (27, "Apertura Sports GmbH");
insert into dim_agent values (28, "IFM");
insert into dim_agent values (29, "Robert Schneider");
insert into dim_agent values (30, "Stellar Football Ltd");
insert into dim_agent values (31, "Pierre-Henri Bovis");
insert into dim_agent values (32, "St. Juste Management");
insert into dim_agent values (33, "BALLWERK Sports GmbH");
insert into dim_agent values (34, "Sports United GmbH");
insert into dim_agent values (35, "PRO Profil GmbH, U23");
insert into dim_agent values (36, "Léandre Chouya");
insert into dim_agent values (37, "Relatives");
insert into dim_agent values (38, "ISMG International");
insert into dim_agent values (39, "IS SPORTS AGENCY ...");
insert into dim_agent values (40, "SBE Management AG");
insert into dim_agent values (41, "Universal Sports ...");
insert into dim_agent values (42, "W&K Fairplay");
insert into dim_agent values (43, "Samii ...");
insert into dim_agent values (44, "Haspel ...");
insert into dim_agent values (45, "Mino Raiola");
insert into dim_agent values (46, "M.A.R.A.T. Football ...");
insert into dim_agent values (47, "Alessandro Lucci - ...");
insert into dim_agent values (48, "no agent");
insert into dim_agent values (49, "Ambition Group");
insert into dim_agent values (50, "Bektas Demirtas");
insert into dim_agent values (51, "Fabryka Futbolu");
insert into dim_agent values (52, "Magnitude Sports & ...");
insert into dim_agent values (53, "Enzo Montepaono");
insert into dim_agent values (54, "Eduardo Uram");
insert into dim_agent values (55, "Fairplay Sports ...");
insert into dim_agent values (56, "TMP SOCCER srl ");
insert into dim_agent values (57, "Gr Sports");
insert into dim_agent values (58, "Manuel García ...");
insert into dim_agent values (59, "Sport 11 AG");
insert into dim_agent values (60, "Grand Stand");
insert into dim_agent values (61, "The Libra Enterprise");
insert into dim_agent values (62, "Wasserman ...");
insert into dim_agent values (63, "ELITE CAREER ...");
insert into dim_agent values (64, "FOOTACT ...");
insert into dim_agent values (65, "LJ Sports & ...");
insert into dim_agent values (66, "Soccer Vision BV");
insert into dim_agent values (67, "IN2-SPORTS");
insert into dim_agent values (68, "Key Sports ...");
insert into dim_agent values (69, "ER Sport Agency");
insert into dim_agent values (70, "World in Motion");
insert into dim_agent values (71, "Agency Nr.1");
insert into dim_agent values (72, "Prestige Sports");
insert into dim_agent values (73, "Premium Stars ...");
insert into dim_agent values (74, "Goal Management");
insert into dim_agent values (75, "Nakhli Mondial");
insert into dim_agent values (76, "PUM");
insert into dim_agent values (77, "Bertolucci Sports");
insert into dim_agent values (78, "BOANERGES");
insert into dim_agent values (79, "Soccer Mondial AG");
insert into dim_agent values (80, "PROMOFUT");
insert into dim_agent values (81, "Forza Sports Group");
insert into dim_agent values (82, "Essel sports ...");
insert into dim_agent values (83, "PROSPORTS Argentina");
insert into dim_agent values (84, "Prime SportBusiness");
insert into dim_agent values (85, "Pietro Chiodi ...");
insert into dim_agent values (86, "Agent is known - player under 18");
insert into dim_agent values (87, "Louis Laros");
insert into dim_agent values (88, "not clarified");
insert into dim_agent values (89, "FM Sports Agency");
insert into dim_agent values (90, "Go Pro Sport ...");
insert into dim_agent values (91, "Elite Consulting ...");
insert into dim_agent values (92, "ProStar");
insert into dim_agent values (93, "Shkumbin Qormemeti");
insert into dim_agent values (94, "UNIDOS");
insert into dim_agent values (95, "Dzhamal Akaev");
insert into dim_agent values (96, "Soccer11");
insert into dim_agent values (97, "Elenko Sports Ltda.");
insert into dim_agent values (98, "Vitaliy Kaloev");
insert into dim_agent values (99, "TZS - TEAMZONEsports");
insert into dim_agent values (100, "Agencia de Futbol ...");
insert into dim_agent values (101, "NESTA SPORT GROUP");
insert into dim_agent values (102, "Leaderbrock Sports");
insert into dim_agent values (103, "TOP VALUE");
insert into dim_agent values (104, "Gestifute");
insert into dim_agent values (105, "ABADSPORT");
insert into dim_agent values (106, "Bahía Internacional");
insert into dim_agent values (107, "HCM Sports ...");
insert into dim_agent values (108, "MRHfutbol");
insert into dim_agent values (109, "Family & Football");
insert into dim_agent values (110, "Implica-T");
insert into dim_agent values (111, "IDUB GLOBAL");
insert into dim_agent values (112, "ACRsoccer");
insert into dim_agent values (113, "Simply Sport ...");
insert into dim_agent values (114, "score agencies");
insert into dim_agent values (115, "fair-sport GmbH");
insert into dim_agent values (116, "KIN");
insert into dim_agent values (117, "TFM Agency");
insert into dim_agent values (118, "Signature - ISCM AG");
insert into dim_agent values (119, "Konstantinos Farras");
insert into dim_agent values (120, "Oscar Bentancourt");
insert into dim_agent values (121, "Midas Sports");
insert into dim_agent values (122, "NABE M&C");
insert into dim_agent values (123, "Elite Project Group ...");
insert into dim_agent values (124, "Pavel Andreev");
insert into dim_agent values (125, "VALERIJUS ...");
insert into dim_agent values (126, "Ioan Becali");
insert into dim_agent values (127, "AllMySports");
insert into dim_agent values (128, "ESA");
insert into dim_agent values (129, "INTERFOOTBALL SA");
insert into dim_agent values (130, "Guanabara Esportes ...");
insert into dim_agent values (131, "Scouting Team B.V.");
insert into dim_agent values (132, "SA-Football Agency");
insert into dim_agent values (133, "Avid Sports Group");
insert into dim_agent values (134, "AKA Global GmbH");
insert into dim_agent values (135, "MagicPlayers");
insert into dim_agent values (136, "Sergio Berti");
insert into dim_agent values (137, "GG11 s.r.l.");
insert into dim_agent values (138, "Omni-Sports");
insert into dim_agent values (139, "SportsMaxi ...");
insert into dim_agent values (140, "Vigo Global Sport ...");
insert into dim_agent values (141, "Irfan Redžepagic");
insert into dim_agent values (142, "Football Management ...");
insert into dim_agent values (143, "Dodici");
insert into dim_agent values (144, "Calenda, Roberto");
insert into dim_agent values (145, "Reset Group Srl");
insert into dim_agent values (146, "GP Soccer and ...");
insert into dim_agent values (147, "OneTwo Sports ...");
insert into dim_agent values (148, "Football Trade");
insert into dim_agent values (149, "Carlos Leite");
insert into dim_agent values (150, "Wonder Sports");
insert into dim_agent values (151, "YMU Group");
insert into dim_agent values (152, "Allthewayup Sports");
insert into dim_agent values (153, "Base Soccer Agency ...");
insert into dim_agent values (154, "Coda Independent ...");
insert into dim_agent values (155, "Pharos Sport Agency");
insert into dim_agent values (156, "DW Sports Management");
insert into dim_agent values (157, "Straight Ace Sports");
insert into dim_agent values (158, "New Era Global ...");
insert into dim_agent values (159, "Jim Solbakken");
insert into dim_agent values (160, "10Ten Football");
insert into dim_agent values (161, "Football Capital");
insert into dim_agent values (162, "PDP s.r.l.  ...");
insert into dim_agent values (163, "Villarreal, Schena ...");
insert into dim_agent values (164, "Box to Box");
insert into dim_agent values (165, "Univers Management");
insert into dim_agent values (166, "AR Sport Management");
insert into dim_agent values (167, "Marko Naletilic");
insert into dim_agent values (168, "Sportlex Srl");
insert into dim_agent values (169, "Madeira Sports");
insert into dim_agent values (170, "ESHA");
insert into dim_agent values (171, "Beckster SPRL");
insert into dim_agent values (172, "SportLife Management");
insert into dim_agent values (173, "RGFOOTBALL");
insert into dim_agent values (174, "Acción Sport");
insert into dim_agent values (175, "Jesus Medina Martin");
insert into dim_agent values (176, "Soccertalents");
insert into dim_agent values (177, "RMD Sport Manager");
insert into dim_agent values (178, "Media Base Sports");
insert into dim_agent values (179, "Augustin Jimenez");
insert into dim_agent values (180, "Soccerrelations");
insert into dim_agent values (181, "CANTERA LATINA / ...");
insert into dim_agent values (182, "Miha Mlakar");
insert into dim_agent values (183, "Soccer ProMaster");
insert into dim_agent values (184, "VIDA 11");
insert into dim_agent values (185, "Gesport Espizua SL");
insert into dim_agent values (186, "Zarko Pelicic");
insert into dim_agent values (187, "JJ SPORT MANAGERS SL");
insert into dim_agent values (188, "ESA Soccer");
insert into dim_agent values (189, "Emefie Aneke Atta");
insert into dim_agent values (190, "NSKY");
insert into dim_agent values (191, "Muy Manero");
insert into dim_agent values (192, "FFP");
insert into dim_agent values (193, "HEROE");
insert into dim_agent values (194, "MR Sport Management ...");
insert into dim_agent values (195, "HAGMAYR ...");
insert into dim_agent values (196, "Fernando Felicevich");
insert into dim_agent values (197, "me(h)rsport GmbH & ...");
insert into dim_agent values (198, "CN Sports");
insert into dim_agent values (199, "Spielerrat GmbH");
insert into dim_agent values (200, "KL Sportsbase");
insert into dim_agent values (201, "Phoenix Sports ...");
insert into dim_agent values (202, "Pedro Aldave");
insert into dim_agent values (203, "Soccer-Concept AG");
insert into dim_agent values (204, "Carmenta");
insert into dim_agent values (205, "Rechtsanwalt ...");
insert into dim_agent values (206, "Frederic Guerra");
insert into dim_agent values (207, "Together For You");
insert into dim_agent values (208, "Jörg Neubauer");
insert into dim_agent values (209, "YA'ATS SPORTS");
insert into dim_agent values (210, "Karlheinz Förster");
insert into dim_agent values (211, "Sports Invest UK ltd");
insert into dim_agent values (212, "Pinhas Zahavi");
insert into dim_agent values (213, "BMS Sportconsulting ...");
insert into dim_agent values (214, "The Player ...");
insert into dim_agent values (215, "Leaguepro LDA");
insert into dim_agent values (216, "PR10");
insert into dim_agent values (217, "Proeleven Gestão ...");
insert into dim_agent values (218, "Invictus Team");
insert into dim_agent values (219, "OFSPORTS");
insert into dim_agent values (220, "ASR SPORT");
insert into dim_agent values (221, "BS & PARTNERS");
insert into dim_agent values (222, "AGN Football");
insert into dim_agent values (223, "NCfoot");
insert into dim_agent values (224, "Edenresults");
insert into dim_agent values (225, "Colombiagol SAS");
insert into dim_agent values (226, "Ulisses Santos - ...");
insert into dim_agent values (227, "athletes first");
insert into dim_agent values (228, "Paulo Barbosa");
insert into dim_agent values (229, "Wimbi Foot");
insert into dim_agent values (230, "IDOLOÁSIS");
insert into dim_agent values (231, "Wasserman");
insert into dim_agent values (232, "EUROFOOT BV");
insert into dim_agent values (233, "Juzzt Football");
insert into dim_agent values (234, "ZILE FOOTBALL ...");
insert into dim_agent values (235, "Soccerfriends ...");
insert into dim_agent values (236, "Falsenine");
insert into dim_agent values (237, "Bruno Carvalho");
insert into dim_agent values (238, "Pavlos Diannis");
insert into dim_agent values (239, "POSITIONUMBER");
insert into dim_agent values (240, "Firstfute Football ...");
insert into dim_agent values (241, "D-Sports");
insert into dim_agent values (242, "Prodigy Players");
insert into dim_agent values (243, "Onsoccer");
insert into dim_agent values (244, "PPSports");
insert into dim_agent values (245, "Footconect Fma");
insert into dim_agent values (246, "La Squadra Sports - ...");
insert into dim_agent values (247, "Domenica Sports ...");
insert into dim_agent values (248, "Marcio Bittencourt ...");
insert into dim_agent values (249, "Global 11");
insert into dim_agent values (250, "MNM Sports ...");
insert into dim_agent values (251, "Jorge Duarte ");
insert into dim_agent values (252, "CMR SPORTS & ...");
insert into dim_agent values (253, "macospo");
insert into dim_agent values (254, "WBD Sports");
insert into dim_agent values (255, "Goodman Sports");
insert into dim_agent values (256, "PW SOCCER ...");
insert into dim_agent values (257, "Branchini Associati ...");
insert into dim_agent values (258, "MB Sports");
insert into dim_agent values (259, "Oscar Damiani");
insert into dim_agent values (260, "B2F");
insert into dim_agent values (261, "Giuseppe Accardi");
insert into dim_agent values (262, "SPORT INVEST ...");
insert into dim_agent values (263, "Football Now Limited");
insert into dim_agent values (264, "MD Management");
insert into dim_agent values (265, "Francesco Romano");
insert into dim_agent values (266, "OLLER GROUP");
insert into dim_agent values (267, "Supporter Management");
insert into dim_agent values (268, "Winny Haatrecht");
insert into dim_agent values (269, "JEB Entertainment ...");
insert into dim_agent values (270, "FOOTFEEL ISM");
insert into dim_agent values (271, "Nomi Sports");
insert into dim_agent values (272, "Boutique Transfers");
insert into dim_agent values (273, "BMG-SPORT");
insert into dim_agent values (274, "ISM Int. Soccer ...");
insert into dim_agent values (275, "HMH Sportmanagement");
insert into dim_agent values (276, "Toldra Consulting ...");
insert into dim_agent values (277, "people in sport");
insert into dim_agent values (278, "S.C. Sports ...");
insert into dim_agent values (279, "ONSIDE");
insert into dim_agent values (280, "Dr. Gutfleisch");
insert into dim_agent values (281, "ASBW Sport Marketing");
insert into dim_agent values (282, "Stars & Friends");
insert into dim_agent values (283, "Sport Avenir ...");
insert into dim_agent values (284, "FPA Fairplay Agency ...");
insert into dim_agent values (285, "Dr. Michael Becker");
insert into dim_agent values (286, "Fröhlich ...");
insert into dim_agent values (287, "Unique Sports ...");
insert into dim_agent values (288, "Volenti");
insert into dim_agent values (289, "Kick & Law");
insert into dim_agent values (290, "ML-Players");
insert into dim_agent values (291, "Beswicks Sports Ltd");
insert into dim_agent values (292, "Platinum One Group");
insert into dim_agent values (293, "Intergol B&S");
insert into dim_agent values (294, "MC Striker");
insert into dim_agent values (295, "Bucket Group ...");
insert into dim_agent values (296, "PromoSport");
insert into dim_agent values (297, "D20 Sports");
insert into dim_agent values (298, "Dynamic Winners");
insert into dim_agent values (299, "Sports Global");
insert into dim_agent values (300, "Fortitude Player ...");
insert into dim_agent values (301, "YOU FIRST SPORTS ");
insert into dim_agent values (302, "Nehoda Sport");
insert into dim_agent values (303, "Giuseppe Galli");
insert into dim_agent values (304, "BSA srl");
insert into dim_agent values (305, "P&P Sport ...");
insert into dim_agent values (306, "Davide Torchia");
insert into dim_agent values (307, "Perspective ...");
insert into dim_agent values (308, "K2K Sports ...");
insert into dim_agent values (309, "Bigpoint");
insert into dim_agent values (310, "Marco Mignini");
insert into dim_agent values (311, "Football Service ...");
insert into dim_agent values (312, "Roberto La Florio");
insert into dim_agent values (313, "Pagliari & Minieri ...");
insert into dim_agent values (314, "Pro Legal Group");
insert into dim_agent values (315, "AFFG/Wasserman");
insert into dim_agent values (316, "JC ...");
insert into dim_agent values (317, "TDS SPORTS");
insert into dim_agent values (318, "ANTHONY FINNIGAN ...");
insert into dim_agent values (319, "D&S Sports ...");
insert into dim_agent values (320, "FOOTBOOK");
insert into dim_agent values (321, "SMI Sports ...");
insert into dim_agent values (322, "Lev Entertainment ...");
insert into dim_agent values (323, "InterLex Sport");
insert into dim_agent values (324, "Fortitude Sports ...");
insert into dim_agent values (325, "CHOVANECSPORT");
insert into dim_agent values (326, "Identity Sports ...");
insert into dim_agent values (327, "Dynamic Agency");
insert into dim_agent values (328, "Primotempo");
insert into dim_agent values (329, "GLOBAL ASES");
insert into dim_agent values (330, "ELITE INTERNACIONAL ...");
insert into dim_agent values (331, "InterStarDeporte");
insert into dim_agent values (332, "Football Promotions ...");
insert into dim_agent values (333, "Promoesport ...");
insert into dim_agent values (334, "MS-Coachings GmbH");
insert into dim_agent values (335, "Antonio Dell´Aglio");
insert into dim_agent values (336, "Leo Rodriguez");
insert into dim_agent values (337, "KGM Sports");
insert into dim_agent values (338, "Fiorio Management ...");
insert into dim_agent values (339, "All Stars Managament");
insert into dim_agent values (340, "JSPORTS MANAGEMENT ...");
insert into dim_agent values (341, "SFI");
insert into dim_agent values (342, "AC Sport Consulting");
insert into dim_agent values (343, "Avv. Filippo Pirisi");
insert into dim_agent values (344, "JV SPORTS SL");
insert into dim_agent values (345, "10Management");
insert into dim_agent values (346, "Christophe Henrotay");
insert into dim_agent values (347, "MESAS SPORT");
insert into dim_agent values (348, "Sergio Esayan");
insert into dim_agent values (349, "RR-Soccer ...");
insert into dim_agent values (350, "90 Sports UK");
insert into dim_agent values (351, "RRNASoccer ...");
insert into dim_agent values (352, "JM10 SPORT");
insert into dim_agent values (353, "starbox");
insert into dim_agent values (354, "F.J.VILLAVERDE");
insert into dim_agent values (355, "Minguella Football ...");
insert into dim_agent values (356, "FOOTALENT");
insert into dim_agent values (357, "Eugenio Botas ...");
insert into dim_agent values (358, "FairSport");
insert into dim_agent values (359, "SPOCS Global sports ...");
insert into dim_agent values (360, "TF");
insert into dim_agent values (361, "Let's Play");
insert into dim_agent values (362, "Matteo Materazzi");
insert into dim_agent values (363, "Creative & ...");
insert into dim_agent values (364, "Emal Wardak Sales");
insert into dim_agent values (365, "Agence 442");
insert into dim_agent values (366, "GROUPE USM");
insert into dim_agent values (367, "BS Group - BS Law");
insert into dim_agent values (368, "firsteleven ISM");
insert into dim_agent values (369, "SEM Group plc.");
insert into dim_agent values (370, "PIVETEAU");
insert into dim_agent values (371, "GM FOOT");
insert into dim_agent values (372, "The Players Club");
insert into dim_agent values (373, "SPORTBACK");
insert into dim_agent values (374, "Sarcle Co. Ltd.");
insert into dim_agent values (375, "Pro Soccer Agent");
insert into dim_agent values (376, "firsteleven ISM ...");
insert into dim_agent values (377, "StarFactory");
insert into dim_agent values (378, "Meïssa N'diaye");
insert into dim_agent values (379, "Michael Manuello");
insert into dim_agent values (380, "Sports Promotion ...");
insert into dim_agent values (381, "J&S International");
insert into dim_agent values (382, "AGROUP");
insert into dim_agent values (383, "Patrick Bastianelli");
insert into dim_agent values (384, "Alliance ...");
insert into dim_agent values (385, "Paco Casal");
insert into dim_agent values (386, "Agent is known NA player under 18");
insert into dim_agent values (387, "Eleven Management");
insert into dim_agent values (388, "Mondial Promotion");
insert into dim_agent values (389, "Stirr Associates");
insert into dim_agent values (390, "Ivan Cvjetkovic");
insert into dim_agent values (391, "B11");
insert into dim_agent values (392, "Global Soccer ...");
insert into dim_agent values (393, "Eris Kismet");
insert into dim_agent values (394, "StormSportsX");
insert into dim_agent values (395, "Panthera Sports");
insert into dim_agent values (396, "SM Sport Assist");
insert into dim_agent values (397, "JCRsport");
insert into dim_agent values (398, "Marat Archegov");
insert into dim_agent values (399, "APS");
insert into dim_agent values (400, "Global Football ...");
insert into dim_agent values (401, "ASA");
insert into dim_agent values (402, "Vukmil Vukmirica");
insert into dim_agent values (403, "RHODES");
insert into dim_agent values (404, "Agencia Brasil");
insert into dim_agent values (405, "NAMED SPORTS ...");
insert into dim_agent values (406, "JAPAN SPORTS ...");
insert into dim_agent values (407, "Mike Barros");
insert into dim_agent values (408, "More than Sport GmbH");
insert into dim_agent values (409, "Footinvest ...");
insert into dim_agent values (410, "TF Tribe");
insert into dim_agent values (411, "Professional Sports ...");
insert into dim_agent values (412, "FOOT EXPANSION");
insert into dim_agent values (413, "Aron Management");
insert into dim_agent values (414, "T.P.O");
insert into dim_agent values (415, "Oxysports TM");
insert into dim_agent values (416, "Cosmosport");
insert into dim_agent values (417, "MASALA FOOTBALL ...");
insert into dim_agent values (418, "CSM");
insert into dim_agent values (419, "Sport Profile");
insert into dim_agent values (420, "OML Sport & ...");
insert into dim_agent values (421, "Classico Sports ...");
insert into dim_agent values (422, "Trivela SM");
insert into dim_agent values (423, "PSC");
insert into dim_agent values (424, "Total Football");
insert into dim_agent values (425, "Crown Football Ltd");
insert into dim_agent values (426, "Milko Banski");
insert into dim_agent values (427, "prosm");
insert into dim_agent values (428, "Soccermax");
insert into dim_agent values (429, "ME");
insert into dim_agent values (430, "Sa Ka Consulting");
insert into dim_agent values (431, "S-C&M");
insert into dim_agent values (432, "MARTIN RIHA");
insert into dim_agent values (433, "Elite Consulting");
insert into dim_agent values (434, "think forward");
insert into dim_agent values (435, "Roberto Tukada");
insert into dim_agent values (436, "Front Group GmbH");
insert into dim_agent values (437, "INTERNATIONAL ...");
insert into dim_agent values (438, "Optimum Football ...");
insert into dim_agent values (439, "Thorsten Nuhn");
insert into dim_agent values (440, "Drazan Gilja");
insert into dim_agent values (441, "ROGON U23");
insert into dim_agent values (442, "Sports and ...");
insert into dim_agent values (443, "Global Sports ...");
insert into dim_agent values (444, "Best of You");
insert into dim_agent values (445, "Ostenkurve");
insert into dim_agent values (446, "TACTIC GRUP - ...");
insert into dim_agent values (447, "Jose Fouto y ...");
insert into dim_agent values (448, "Twenty Two S.A.");
insert into dim_agent values (449, "Eleven Talent Group");
insert into dim_agent values (450, "Feel Winner");
insert into dim_agent values (451, "World Football");
insert into dim_agent values (452, "Senol Tosun Sports ...");
insert into dim_agent values (453, "Supervision ...");
insert into dim_agent values (454, "Bernard Collignon");
insert into dim_agent values (455, "Team Spirit ...");
insert into dim_agent values (456, "Velasco Sport Group");
insert into dim_agent values (457, "GMRsports");
insert into dim_agent values (458, "Serafino Luzzi");
insert into dim_agent values (459, "JB Sports Group GmbH");
insert into dim_agent values (460, "Kubacki Marcin");
insert into dim_agent values (461, "KICK & RUN SPORTS");
insert into dim_agent values (462, "WINStar Management ");
insert into dim_agent values (463, "EMG Mundial");
insert into dim_agent values (464, "SMG GmbH");
insert into dim_agent values (465, "D+R Dahm Richter ...");
insert into dim_agent values (466, "ProSC");
insert into dim_agent values (467, "Hi Talent");
insert into dim_agent values (468, "PLAYERSAGENCY");
insert into dim_agent values (469, "Triple S Sports");
insert into dim_agent values (470, "Sbsfoot");
insert into dim_agent values (471, "Lions Sports AG");
insert into dim_agent values (472, "Championsdek");
insert into dim_agent values (473, "Jorge Pires");
insert into dim_agent values (474, "ULTRA SOCCER");
insert into dim_agent values (475, "Eden Sports Group");
insert into dim_agent values (476, "Igor Gluscevic");
insert into dim_agent values (477, "ROYAL");
insert into dim_agent values (478, "WELT SPORTS");
insert into dim_agent values (479, "Rummenigge Sport ...");
insert into dim_agent values (480, "JB Sports2Business ...");
insert into dim_agent values (481, "Think Ball & Sports ...");
insert into dim_agent values (482, "MSG-Agency");
insert into dim_agent values (483, "90m");
insert into dim_agent values (484, "YOUnited Management ...");
insert into dim_agent values (485, "NGM SPORTS");
insert into dim_agent values (486, "Colossal Sports ...");
insert into dim_agent values (487, "teambbc");
insert into dim_agent values (488, "Puyol, De la Peña ...");
insert into dim_agent values (489, "AC Talent");
insert into dim_agent values (490, "Perfect Element BV");
insert into dim_agent values (491, "Eijkelkamp Pro ...");
insert into dim_agent values (492, "Soccer-Solutions");
insert into dim_agent values (493, "Mesut Eslik");
insert into dim_agent values (494, "Gorré Soccer ...");
insert into dim_agent values (495, "HBR Sport");
insert into dim_agent values (496, "AGREF");
insert into dim_agent values (497, "Futuralis Football ...");
insert into dim_agent values (498, "M&V sport management");
insert into dim_agent values (499, "NOACK SPORTS GmbH");
insert into dim_agent values (500, "PESM");
insert into dim_agent values (501, "WSB Soccer");
insert into dim_agent values (502, "ARGENTUM SPORT");
insert into dim_agent values (503, "3A");
insert into dim_agent values (504, "Loïc BENSAÏD");
insert into dim_agent values (505, "forward management ...");
insert into dim_agent values (506, "Just 4 player Group");
insert into dim_agent values (507, "Pinnacle Global ...");
insert into dim_agent values (508, "FS Management");
insert into dim_agent values (509, "SB Sports");
insert into dim_agent values (510, "Jennifer ...");
insert into dim_agent values (511, "TTMIB Worldwide");
insert into dim_agent values (512, "Kuniy & W. Sports ...");
insert into dim_agent values (513, "NL-Soccer");
insert into dim_agent values (514, "LIFEPRO");
insert into dim_agent values (515, "H2C Sport Consulting");
insert into dim_agent values (516, "Lorenz Consulting");
insert into dim_agent values (517, "Onze Sports");
insert into dim_agent values (518, "Latchezar Tanev");
insert into dim_agent values (519, "TEAM MANAGEMENT");
insert into dim_agent values (520, "GR2");
insert into dim_agent values (521, "YBI Sport");
insert into dim_agent values (522, "100and10 ...");
insert into dim_agent values (523, "F-F SPORT");
insert into dim_agent values (524, "Sport Essentials BV");
insert into dim_agent values (525, "FullNinety Sports ...");
insert into dim_agent values (526, "GLOBALL FootBiz ...");
insert into dim_agent values (527, "Chin International ...");
insert into dim_agent values (528, "Pro Athlete");
insert into dim_agent values (529, "Ceasar Sports ...");
insert into dim_agent values (530, "Gold Football");
insert into dim_agent values (531, "Soccertalk GmbH");
insert into dim_agent values (532, "CONTRATTO & GOLLER");
insert into dim_agent values (533, "Prof Partners ...");
insert into dim_agent values (534, "Mariusz Kulesza");
insert into dim_agent values (535, "Alain Migliaccio");
insert into dim_agent values (536, "Guastadisegno");
insert into dim_agent values (537, "BJARNE GOLDBAEK");
insert into dim_agent values (538, "EXCELLENCE SPORT SAS");
insert into dim_agent values (539, "KFM");
insert into dim_agent values (540, "iFootball");
insert into dim_agent values (541, "Alp Sengunler");
insert into dim_agent values (542, "J.Kwasi Siaw");
insert into dim_agent values (543, "Sportconsult ...");
insert into dim_agent values (544, "Francesco Viviani");
insert into dim_agent values (545, "KSirius Football ...");
insert into dim_agent values (546, "FootNation");
insert into dim_agent values (547, "ESN");
insert into dim_agent values (548, "Kemari");
insert into dim_agent values (549, "Art Sports ...");
insert into dim_agent values (550, "Gallea Gestion S.A");
insert into dim_agent values (551, "Ivan Sports Korea");
insert into dim_agent values (552, "Soccerdreamz ...");
insert into dim_agent values (553, "Star-Gol");
insert into dim_agent values (554, "Tim Mescheder");
insert into dim_agent values (555, "Ciro Palermo");
insert into dim_agent values (556, "Barbadillo & ...");
insert into dim_agent values (557, "Carlo Pallavicino");
insert into dim_agent values (558, "PRO TRANSFER");
insert into dim_agent values (559, "Eurofinanzas Sport ");
insert into dim_agent values (560, "Emartsoccer");
insert into dim_agent values (561, "Pedro Bravo - ...");
insert into dim_agent values (562, "Ben Kouider Group");
insert into dim_agent values (563, "Domingo Sevillano ...");
insert into dim_agent values (564, "GBG Global Business ...");
insert into dim_agent values (565, "Footunited - João ...");
insert into dim_agent values (566, "MNV");
insert into dim_agent values (567, "AD SPORTS");
insert into dim_agent values (568, "CSM Sport & ...");
insert into dim_agent values (569, "GISMAN-The ...");
insert into dim_agent values (570, "DL Sport Management");
insert into dim_agent values (571, "Sporting11");
insert into dim_agent values (572, "B.A.Quality Players ");
insert into dim_agent values (573, "GRINTA");
insert into dim_agent values (574, "D.E.R.S. group");
insert into dim_agent values (575, "PARRI GROUP");
insert into dim_agent values (576, "Pro Athletes");
insert into dim_agent values (577, "MSG");
insert into dim_agent values (578, "Seven stars");
insert into dim_agent values (579, "Jonas Svensson ...");
insert into dim_agent values (580, "IN2NASPORTS");
insert into dim_agent values (581, "Football Total");
insert into dim_agent values (582, "Neil Mason");
insert into dim_agent values (583, "G.E.V. ...");
insert into dim_agent values (584, "CSM Agency");
insert into dim_agent values (585, "Gianni Vitali");
insert into dim_agent values (586, "INNfootball");
insert into dim_agent values (587, "Roggi ...");
insert into dim_agent values (588, "T&M International");
insert into dim_agent values (589, "Sports Advice ...");
insert into dim_agent values (590, "11one");
insert into dim_agent values (591, "Teamgeist ...");
insert into dim_agent values (592, "ELISPRO");
insert into dim_agent values (593, "Sports Revolution");
insert into dim_agent values (594, "TSH Talentschmiede ...");
insert into dim_agent values (595, "More Than Goals");
insert into dim_agent values (596, "Briem Soccer ...");
insert into dim_agent values (597, "Management 15");
insert into dim_agent values (598, "Assist");
insert into dim_agent values (599, "Miroslav Bicanic");
insert into dim_agent values (600, "AGB Sport Management");
insert into dim_agent values (601, "Barry Hulshoff");
insert into dim_agent values (602, "Back Sports S.A.");
insert into dim_agent values (603, "Riosfutbol");
insert into dim_agent values (604, "LLC FT COMPANY");
insert into dim_agent values (605, "Vision Foot");
insert into dim_agent values (606, "Axia Sports ...");
insert into dim_agent values (607, "International Sport ...");
insert into dim_agent values (608, "Kick Off Management");
insert into dim_agent values (609, "World Sports ...");
insert into dim_agent values (610, "GBS Group ...");
insert into dim_agent values (611, "Maurizio Morana and ...");
insert into dim_agent values (612, "NCHsports");
insert into dim_agent values (613, "SIP Sports");
insert into dim_agent values (614, "Miami stars ...");
insert into dim_agent values (615, "Sportfront GmbH");
insert into dim_agent values (616, "Cherry Sports");
insert into dim_agent values (617, "Playmaker Football ...");
insert into dim_agent values (618, "F-MG.com");
insert into dim_agent values (619, "Humberto Quiceno");
insert into dim_agent values (620, "DS-Management");
insert into dim_agent values (621, "myyk.inc");
insert into dim_agent values (622, "BSSM");
insert into dim_agent values (623, "Keypass AS");
insert into dim_agent values (624, "MATCHING SPORT");
insert into dim_agent values (625, "Germania ...");
insert into dim_agent values (626, "CID Marinescu");
insert into dim_agent values (627, "DAS Sports ...");
insert into dim_agent values (628, "DOO Magnum");
insert into dim_agent values (629, "MCV Sports");
insert into dim_agent values (630, "Gea World S.p.A.");
insert into dim_agent values (631, "IFManagement");
insert into dim_agent values (632, "SMI");
insert into dim_agent values (633, "WATI-SPORT");
insert into dim_agent values (634, "STV ");
insert into dim_agent values (635, "Italian Managers ...");
insert into dim_agent values (636, "Filippo Cavadini");
insert into dim_agent values (637, "Gest Eleven");
insert into dim_agent values (638, "Mateja Kezman");
insert into dim_agent values (639, "GM Sports Management");
insert into dim_agent values (640, "FK Sport Management ...");
insert into dim_agent values (641, "BSM");
insert into dim_agent values (642, "23 Football ...");
insert into dim_agent values (643, "dtsm");
insert into dim_agent values (644, "Grimaldi Mariano");
insert into dim_agent values (645, "Starbridge Srl");
insert into dim_agent values (646, "TGsoccer Srls");
insert into dim_agent values (647, "Palomba ...");
insert into dim_agent values (648, "Kael Grimaldi");
insert into dim_agent values (649, "TUR_SA");
insert into dim_agent values (650, "ACE Management");
insert into dim_agent values (651, "HSD");
insert into dim_agent values (652, "W.Egal O.S.F.M.");
insert into dim_agent values (653, "Rafael Anguita");
insert into dim_agent values (654, "SPAIN SPORT ...");
insert into dim_agent values (655, "Sport Agency 4U");
insert into dim_agent values (656, "NWS - Neis World ...");
insert into dim_agent values (657, "UK Sport Management ...");
insert into dim_agent values (658, "Football Mix B.V.");
insert into dim_agent values (659, "Raps Management");
insert into dim_agent values (660, "Dimitri Celuk");
insert into dim_agent values (661, "REDDE");
insert into dim_agent values (662, "EKIPA");
insert into dim_agent values (663, "Trust Football ");
insert into dim_agent values (664, "Blueprivate ...");
insert into dim_agent values (665, "Glory Soccer Agency");
insert into dim_agent values (666, "International Foot");
insert into dim_agent values (667, "Asportsmanagement");
insert into dim_agent values (668, "Cristiano Simões");
insert into dim_agent values (669, "Anatoliy Patuk");
insert into dim_agent values (670, "Pablo Barquero");
insert into dim_agent values (671, "USFA Management");
insert into dim_agent values (672, "Special1Agency");
insert into dim_agent values (673, "CONACTA INC");
insert into dim_agent values (674, "Teixeira Players ...");
insert into dim_agent values (675, "Brazil Football");
insert into dim_agent values (676, "GOLDEN SOCCER SPORTS");
insert into dim_agent values (677, "Sferico Sports ...");
insert into dim_agent values (678, "Arandilla Calcio y ...");
insert into dim_agent values (679, "MZ Esportes Group");
insert into dim_agent values (680, "Wolfgang Meier ...");
insert into dim_agent values (681, "MFS - Managing ...");
insert into dim_agent values (682, "Christian Bragarnik");
insert into dim_agent values (683, "Isportsa");
insert into dim_agent values (684, "Sportsantho");
insert into dim_agent values (685, "Darren Dein");
insert into dim_agent values (686, "KBM");
insert into dim_agent values (687, "Altis ...");
insert into dim_agent values (688, "TRDS");
insert into dim_agent values (689, "fAirplay-Management");
insert into dim_agent values (690, "Global Compensation");
insert into dim_agent values (691, "MEDIATION CONSEIL ...");
insert into dim_agent values (692, "CH Conseil et ...");
insert into dim_agent values (693, "Siyavuma");
insert into dim_agent values (694, "Red ball agency");
insert into dim_agent values (695, "DH Sports.pt");
insert into dim_agent values (696, "Atticus Sports ...");
insert into dim_agent values (697, "PELIKAN AGENCY Inc");
insert into dim_agent values (698, "Sportsbloom");
insert into dim_agent values (699, "Alpha sports ...");
insert into dim_agent values (700, "PODIA SPORTS LTD");
insert into dim_agent values (701, "Global Sports Agent ...");
insert into dim_agent values (702, "Football Marketing");
insert into dim_agent values (703, "AMQ Attorney at law");
insert into dim_agent values (704, "SAO");
insert into dim_agent values (705, "Eoxxon Sports Group");
insert into dim_agent values (706, "Carrierefoot");
insert into dim_agent values (707, "L-concept Sports");
insert into dim_agent values (708, "Careerkick");
insert into dim_agent values (709, "Boll Brands");
insert into dim_agent values (710, "Giallanza Sport");
insert into dim_agent values (711, "Henri Zambelli");
insert into dim_agent values (712, "Marcus Marin");
insert into dim_agent values (713, "BK Partners Group");
insert into dim_agent values (714, "CLK FOOT");
insert into dim_agent values (715, "MCP Sport ...");
insert into dim_agent values (716, "Mansa Sports ...");
insert into dim_agent values (717, "NIM-Group Sport ...");
insert into dim_agent values (718, "PFN");
insert into dim_agent values (719, "uscout.ru");
insert into dim_agent values (720, "BHM Sports Agency");
insert into dim_agent values (721, "ST Management");
insert into dim_agent values (722, "IFM-M");
insert into dim_agent values (723, "B&D INTERNATIONAL ...");
insert into dim_agent values (724, "AKI&DESIDERIO");
insert into dim_agent values (725, "Amin Sakman");
insert into dim_agent values (726, "CTS-SMI ");
insert into dim_agent values (727, "SpoCoNet");
insert into dim_agent values (728, "Victrix");
insert into dim_agent values (729, "Mickael Libong");
insert into dim_agent values (730, "M Sab");
insert into dim_agent values (731, "Professional ...");
insert into dim_agent values (732, "Paulo Tonietto");
insert into dim_agent values (733, "Players Promotion ");
insert into dim_agent values (734, "Football Service");
insert into dim_agent values (735, "Fútbol División");
insert into dim_agent values (736, "eightyfive sa");
insert into dim_agent values (737, "Sopranzi Samuele");
insert into dim_agent values (738, "Football Company Srl");
insert into dim_agent values (739, "Bugra Coskun");
insert into dim_agent values (740, "Paul Vilhena");
insert into dim_agent values (741, "Sync Global Sports");
insert into dim_agent values (742, "Brazilsport");
insert into dim_agent values (743, "Henrique Pompeo");
insert into dim_agent values (744, "Ellite Sports");
insert into dim_agent values (745, "Catió Baldé");
insert into dim_agent values (746, "SPORTS ACTION");
insert into dim_agent values (747, "MP Management");
insert into dim_agent values (748, "P.P.M.");
insert into dim_agent values (749, "Europ Sport ...");
insert into dim_agent values (750, "PEP Consulting");
insert into dim_agent values (751, "4FC");
insert into dim_agent values (752, "CSGG");
insert into dim_agent values (753, "Davor Curkovic");
insert into dim_agent values (754, "IMASPORT");
insert into dim_agent values (755, "Mladen Grgic");
insert into dim_agent values (756, "PROTIO SPORT");
insert into dim_agent values (757, "EURODATA SPORT");
insert into dim_agent values (758, "Prime Time Sport");
insert into dim_agent values (759, "FIA Sports ...");
insert into dim_agent values (760, "PitZGroup");
insert into dim_agent values (761, "Ginés Carvajal");
insert into dim_agent values (762, "Horacio Gaggioli");
insert into dim_agent values (763, "Un1que football");
insert into dim_agent values (764, "IDV");
insert into dim_agent values (765, "David BONNAN");
insert into dim_agent values (766, "Dini");
insert into dim_agent values (767, "Sigma Foot");
insert into dim_agent values (768, "SPORTS CONNECTION");
insert into dim_agent values (769, "Vlado Bozinoski");
insert into dim_agent values (770, "PRO PLAYERS ASSOCIES");
insert into dim_agent values (771, "ND SPORTS MANAGEMENT");
insert into dim_agent values (772, "AGCC");
insert into dim_agent values (773, "exclusive Sports GbR");
insert into dim_agent values (774, "Sports Winners ...");
insert into dim_agent values (775, "Remington Cherin");
insert into dim_agent values (776, "Kita Sport");
insert into dim_agent values (777, "Rüdiger Bernatek");
insert into dim_agent values (778, "Sportconsult SA");
insert into dim_agent values (779, "Vasilev & Co. ...");
insert into dim_agent values (780, "First Access Sports");
insert into dim_agent values (781, "Football+ CM");
insert into dim_agent values (782, "Remi Wulff");
insert into dim_agent values (783, "PROFI-MANAGEMENT");
insert into dim_agent values (784, "Dudu Dahan");
insert into dim_agent values (785, "Connect Management");
insert into dim_agent values (786, "Bolat Management");
insert into dim_agent values (787, "Christian Pala");
insert into dim_agent values (788, "A.S. Management");
insert into dim_agent values (789, "Mega Sports");
insert into dim_agent values (790, "Prosport ...");
insert into dim_agent values (791, "MK Sport Consulting");
insert into dim_agent values (792, "Luis Management");
insert into dim_agent values (793, "CFM");
insert into dim_agent values (794, "Aziz Ndiaye");
insert into dim_agent values (795, "Jwtiar Khalid Rahman");
insert into dim_agent values (796, "SLWORLDTEAM");
insert into dim_agent values (797, "Japan at UK limited");
insert into dim_agent values (798, "Rosko Company");
insert into dim_agent values (799, "New Player AS");
insert into dim_agent values (800, "NSTM");
insert into dim_agent values (801, "FMG");
insert into dim_agent values (802, "Ivan Bosnjak");
insert into dim_agent values (803, "Hawk Football");
insert into dim_agent values (804, "FSA");
insert into dim_agent values (805, "Love Players");
insert into dim_agent values (806, "O. Gardarsson & ...");
insert into dim_agent values (807, "Ellipse Agency");
insert into dim_agent values (808, "Amc sport paris ");
insert into dim_agent values (809, "Martin Klette");
insert into dim_agent values (810, "Riccardo Calleri");
insert into dim_agent values (811, "Cheikh Fall");
insert into dim_agent values (812, "Dedra Football ...");
insert into dim_agent values (813, "B&S Football ...");
insert into dim_agent values (814, "PROSPORT Management");
insert into dim_agent values (815, "Soccersport");
insert into dim_agent values (816, "New Star Sport ...");
insert into dim_agent values (817, "Luigi Lauro SBM srl ");
insert into dim_agent values (818, "LG Group Srl");
insert into dim_agent values (819, "Simone Seghedoni");
insert into dim_agent values (820, "Fedele, Gaetano");
insert into dim_agent values (821, "FUTURA 2 SA");
insert into dim_agent values (822, "Castelnovo");
insert into dim_agent values (823, "Prattes Group");
insert into dim_agent values (824, "Top Player Agency");
insert into dim_agent values (825, "Alinea");
insert into dim_agent values (826, "Extra Time Sports ...");
insert into dim_agent values (827, "CLS Mundial");
insert into dim_agent values (828, "ISMA");
insert into dim_agent values (829, "Louis DENOLLE");
insert into dim_agent values (830, "Sportagentur ...");
insert into dim_agent values (831, "Thiede Management");
insert into dim_agent values (832, "EMD Sports GmbH");
insert into dim_agent values (833, "Kay Sports ...");
insert into dim_agent values (834, "SNM Sportmanagement");
insert into dim_agent values (835, "Number 1 Sports GmbH");
insert into dim_agent values (836, "90 Minuten & Mehr ...");
insert into dim_agent values (837, "teamplayer ...");
insert into dim_agent values (838, "PG 120 Sport Agency");
insert into dim_agent values (839, "neblung ...");
insert into dim_agent values (840, "Guido Walter");
insert into dim_agent values (841, "Karl M. Herzog ...");
insert into dim_agent values (842, "EK Sports Management");
insert into dim_agent values (843, "Milan Calasan");
insert into dim_agent values (844, "One Touch Sport ...");
insert into dim_agent values (845, "Joseba Diaz");
insert into dim_agent values (846, "OLYMPiQUE SAN");
insert into dim_agent values (847, "CES");
insert into dim_agent values (848, "Valentin Balongo");
insert into dim_agent values (849, "LionShare");
insert into dim_agent values (850, "Bury Management SPRL");
insert into dim_agent values (851, "Martin van Ophuizen");
insert into dim_agent values (852, "Roger Boli");
insert into dim_agent values (853, "PROhorizons Group");
insert into dim_agent values (854, "F&L");
insert into dim_agent values (855, "Match2gether");
insert into dim_agent values (856, "12 MANagement");
insert into dim_agent values (857, "B&F Sporting sas ");
insert into dim_agent values (858, "Attacantti Sports ...");
insert into dim_agent values (859, "PRO10 Sports");
insert into dim_agent values (860, "Top Sport Services");
insert into dim_agent values (861, "Kick Unit Austria ...");
insert into dim_agent values (862, "Giovanni Damiano ...");
insert into dim_agent values (863, "Ultimate Sports");
insert into dim_agent values (864, "João Alberto Malik ...");
insert into dim_agent values (865, "MVP Group");
insert into dim_agent values (866, "Leonardo Corsi");
insert into dim_agent values (867, "The Talents ...");
insert into dim_agent values (868, "Villarreal & Schena");
insert into dim_agent values (869, "CK66");
insert into dim_agent values (870, "4comM");
insert into dim_agent values (871, "ARETÉ");
insert into dim_agent values (872, "ExtraTime S.L.");
insert into dim_agent values (873, "management 360");
insert into dim_agent values (874, "Global Management ...");
insert into dim_agent values (875, "World Soccer Star ...");
insert into dim_agent values (876, "OG ");
insert into dim_agent values (877, "World of Soccer");
insert into dim_agent values (878, "GM & Associés");
insert into dim_agent values (879, "PMK COMPANY");
insert into dim_agent values (880, "Soccerdome");
insert into dim_agent values (881, "Moussa Ndiaye");
insert into dim_agent values (882, "ZAC");
insert into dim_agent values (883, "Pro Manager Sports ...");
insert into dim_agent values (884, "ST Sportmarketing");
insert into dim_agent values (885, "Paolo Palermo");
insert into dim_agent values (886, "Ariel Krasouski");
insert into dim_agent values (887, "Maxime Nana");
insert into dim_agent values (888, "Friends & Football ...");
insert into dim_agent values (889, "Donato Orgnoni");
insert into dim_agent values (890, "TODER");
insert into dim_agent values (891, "Playeleven");
insert into dim_agent values (892, "Sport Business ...");
insert into dim_agent values (893, "NSG ApS");
insert into dim_agent values (894, "Sport Consulting di ...");
insert into dim_agent values (895, "Royal Project srl");
insert into dim_agent values (896, "Finally FOOTBALL ...");
insert into dim_agent values (897, "TEAMVISION soccer");
insert into dim_agent values (898, "TPWE GmbH");
insert into dim_agent values (899, "Günter Kutowski");
insert into dim_agent values (900, "Frieder Gamm Group ...");
insert into dim_agent values (901, "AF Sport Management");
insert into dim_agent values (902, "Gianluca Di Carlo");
insert into dim_agent values (903, "DA Sport Colsulting");
insert into dim_agent values (904, "CONNEXION");
insert into dim_agent values (905, "INTEAMSPORTS");
insert into dim_agent values (906, "Stephan Engels");
insert into dim_agent values (907, "Ilhan Malli");
insert into dim_agent values (908, "Marcelo Lombilla");
insert into dim_agent values (909, "GK Football");
insert into dim_agent values (910, "Toreta d.o.o.");
insert into dim_agent values (911, "Smart Sports Agency");
insert into dim_agent values (912, "PURE");
insert into dim_agent values (913, "Ethos Group B.V.");
insert into dim_agent values (914, "World Soccer Consult");
insert into dim_agent values (915, "BMG Sports");
insert into dim_agent values (916, "BM SOCCER");
insert into dim_agent values (917, "Super Sport ...");
insert into dim_agent values (918, "AXISFUT");
insert into dim_agent values (919, "Ahannach Sport");
insert into dim_agent values (920, "DBR Sports");
insert into dim_agent values (921, "BBC Management GmbH");
insert into dim_agent values (922, "Gregor Machulik");
insert into dim_agent values (923, "TRP Sports");
insert into dim_agent values (924, "Loyalty Sports ...");
insert into dim_agent values (925, "Shahar Greenberg ...");
insert into dim_agent values (926, "4449 ...");
insert into dim_agent values (927, "Velop4 Sports Ltd.");
insert into dim_agent values (928, "Dirk Lips");
insert into dim_agent values (929, "DLT Sportmanagement");
insert into dim_agent values (930, "Image International ...");
insert into dim_agent values (931, "H.S.P. ...");
insert into dim_agent values (932, "SAM SPORTS");
insert into dim_agent values (933, "acta7");
insert into dim_agent values (934, "ALF Sports GmbH");
insert into dim_agent values (935, "M.AG");
insert into dim_agent values (936, "Aspire Management");
insert into dim_agent values (937, "Sports Genius Agency");
insert into dim_agent values (938, "Element Twelve");
insert into dim_agent values (939, "Grégory Mardian");
insert into dim_agent values (940, "SHINE Entertainment ...");
insert into dim_agent values (941, "Aspire");
insert into dim_agent values (942, "Star Management ...");
insert into dim_agent values (943, "COMUNIGOAL");
insert into dim_agent values (944, "POSSOFUTBOL ");
insert into dim_agent values (945, "FA PLAYERS AGENTS");
insert into dim_agent values (946, "Govan Sports");
