insert into dim_affiliation values (1, "1. FC Koln");
insert into dim_affiliation values (2, "1.FSV Mainz 05");
insert into dim_affiliation values (3, "AC Milan");
insert into dim_affiliation values (4, "ADO Den Haag");
insert into dim_affiliation values (5, "Ajax");
insert into dim_affiliation values (6, "Akhmat Grozny");
insert into dim_affiliation values (7, "Alaves");
insert into dim_affiliation values (8, "Arsenal");
insert into dim_affiliation values (9, "Arsenal Tula");
insert into dim_affiliation values (10, "AS Roma");
insert into dim_affiliation values (11, "Aston Villa");
insert into dim_affiliation values (12, "Atalanta");
insert into dim_affiliation values (13, "Athletic");
insert into dim_affiliation values (14, "Atletico Madrid");
insert into dim_affiliation values (15, "AZ Alkmaar");
insert into dim_affiliation values (16, "Bay. Leverkusen");
insert into dim_affiliation values (17, "Bayern Munich");
insert into dim_affiliation values (18, "Belenenses SAD");
insert into dim_affiliation values (19, "Benfica");
insert into dim_affiliation values (20, "Boavista");
insert into dim_affiliation values (21, "Bologna");
insert into dim_affiliation values (22, "Bor. Dortmund");
insert into dim_affiliation values (23, "Bor. M'gladbach");
insert into dim_affiliation values (24, "Bournemouth");
insert into dim_affiliation values (25, "Braga");
insert into dim_affiliation values (26, "Brescia");
insert into dim_affiliation values (27, "Brighton");
insert into dim_affiliation values (28, "Burnley");
insert into dim_affiliation values (29, "CA Osasuna");
insert into dim_affiliation values (30, "Cagliari Calcio");
insert into dim_affiliation values (31, "CD Leganes");
insert into dim_affiliation values (32, "Celta de Vigo");
insert into dim_affiliation values (33, "Cercle Brugge");
insert into dim_affiliation values (34, "Chelsea");
insert into dim_affiliation values (35, "Club Brugge");
insert into dim_affiliation values (36, "Crystal Palace");
insert into dim_affiliation values (37, "CSKA Moscow");
insert into dim_affiliation values (38, "Desportivo Aves");
insert into dim_affiliation values (39, "Dijon");
insert into dim_affiliation values (40, "Dinamo Moscow");
insert into dim_affiliation values (41, "E. Frankfurt");
insert into dim_affiliation values (42, "Espanyol");
insert into dim_affiliation values (43, "Everton");
insert into dim_affiliation values (44, "F. Dusseldorf");
insert into dim_affiliation values (45, "Famalicao");
insert into dim_affiliation values (46, "FC Augsburg");
insert into dim_affiliation values (47, "FC Barcelona");
insert into dim_affiliation values (48, "FC Emmen");
insert into dim_affiliation values (49, "FC Groningen");
insert into dim_affiliation values (50, "FC Metz");
insert into dim_affiliation values (51, "FC Nantes");
insert into dim_affiliation values (52, "FC Porto");
insert into dim_affiliation values (53, "FC Schalke 04");
insert into dim_affiliation values (54, "FC Twente");
insert into dim_affiliation values (55, "FC Utrecht");
insert into dim_affiliation values (56, "Feyenoord");
insert into dim_affiliation values (57, "Fiorentina");
insert into dim_affiliation values (58, "Fortuna Sittard");
insert into dim_affiliation values (59, "G. Bordeaux");
insert into dim_affiliation values (60, "Genoa");
insert into dim_affiliation values (61, "Getafe");
insert into dim_affiliation values (62, "Gil Vicente");
insert into dim_affiliation values (63, "Granada CF");
insert into dim_affiliation values (64, "Heerenveen");
insert into dim_affiliation values (65, "Hellas Verona");
insert into dim_affiliation values (66, "Heracles Almelo");
insert into dim_affiliation values (67, "Hertha BSC");
insert into dim_affiliation values (68, "Inter");
insert into dim_affiliation values (69, "Juventus");
insert into dim_affiliation values (70, "KAA Gent");
insert into dim_affiliation values (71, "Krasnodar");
insert into dim_affiliation values (72, "KRC Genk");
insert into dim_affiliation values (73, "KS Samara");
insert into dim_affiliation values (74, "Lazio");
insert into dim_affiliation values (75, "Lecce");
insert into dim_affiliation values (76, "Leicester");
insert into dim_affiliation values (77, "Levante");
insert into dim_affiliation values (78, "Liverpool");
insert into dim_affiliation values (79, "Loko Moscow");
insert into dim_affiliation values (80, "LOSC Lille");
insert into dim_affiliation values (81, "Man City");
insert into dim_affiliation values (82, "Man Utd");
insert into dim_affiliation values (83, "Marítimo");
insert into dim_affiliation values (84, "Marseille");
insert into dim_affiliation values (85, "Monaco");
insert into dim_affiliation values (86, "Montpellier");
insert into dim_affiliation values (87, "Moreirense");
insert into dim_affiliation values (88, "Newcastle");
insert into dim_affiliation values (89, "Nimes Olympique");
insert into dim_affiliation values (90, "Norwich");
insert into dim_affiliation values (91, "OGC Nice");
insert into dim_affiliation values (92, "Olympique Lyon");
insert into dim_affiliation values (93, "Orenburg");
insert into dim_affiliation values (94, "Pacos Ferreira");
insert into dim_affiliation values (95, "Paris SG");
insert into dim_affiliation values (96, "Parma");
insert into dim_affiliation values (97, "PEC Zwolle");
insert into dim_affiliation values (98, "Portimonense");
insert into dim_affiliation values (99, "PSV Eindhoven");
insert into dim_affiliation values (100, "R. Strasbourg");
insert into dim_affiliation values (101, "RB Leipzig");
insert into dim_affiliation values (102, "RCD Mallorca");
insert into dim_affiliation values (103, "Real Betis");
insert into dim_affiliation values (104, "Real Madrid");
insert into dim_affiliation values (105, "Real Sociedad");
insert into dim_affiliation values (106, "Real Valladolid");
insert into dim_affiliation values (107, "Reims");
insert into dim_affiliation values (108, "Rio Ave FC");
insert into dim_affiliation values (109, "RKC Waalwijk");
insert into dim_affiliation values (110, "Rostov");
insert into dim_affiliation values (111, "Royal Antwerp");
insert into dim_affiliation values (112, "RSC Anderlecht");
insert into dim_affiliation values (113, "RSC Charleroi");
insert into dim_affiliation values (114, "Rubin Kazan");
insert into dim_affiliation values (115, "Saint-Etienne");
insert into dim_affiliation values (116, "Sampdoria");
insert into dim_affiliation values (117, "Santa Clara");
insert into dim_affiliation values (118, "Sassuolo");
insert into dim_affiliation values (119, "SC Amiens");
insert into dim_affiliation values (120, "SC Freiburg");
insert into dim_affiliation values (121, "SC Paderborn");
insert into dim_affiliation values (122, "SCO Angers");
insert into dim_affiliation values (123, "SD Eibar");
insert into dim_affiliation values (124, "Sevilla FC");
insert into dim_affiliation values (125, "Sheffield Utd.");
insert into dim_affiliation values (126, "Sint-Truiden");
insert into dim_affiliation values (127, "SintNATruiden");
insert into dim_affiliation values (128, "Sochi");
insert into dim_affiliation values (129, "Southampton");
insert into dim_affiliation values (130, "SPAL");
insert into dim_affiliation values (131, "Sparta R.");
insert into dim_affiliation values (132, "Spartak Moscow");
insert into dim_affiliation values (133, "Sporting CP");
insert into dim_affiliation values (134, "Spurs");
insert into dim_affiliation values (135, "SSC Napoli");
insert into dim_affiliation values (136, "Stade Brest 29");
insert into dim_affiliation values (137, "Stade Rennais");
insert into dim_affiliation values (138, "Standard Liege");
insert into dim_affiliation values (139, "Tambov");
insert into dim_affiliation values (140, "Tondela");
insert into dim_affiliation values (141, "Torino");
insert into dim_affiliation values (142, "Toulouse");
insert into dim_affiliation values (143, "TSG Hoffenheim");
insert into dim_affiliation values (144, "Udinese Calcio");
insert into dim_affiliation values (145, "Ufa");
insert into dim_affiliation values (146, "Union Berlin");
insert into dim_affiliation values (147, "Ural");
insert into dim_affiliation values (148, "Valencia");
insert into dim_affiliation values (149, "VfL Wolfsburg");
insert into dim_affiliation values (150, "Villarreal");
insert into dim_affiliation values (151, "Vit. Guimaraes");
insert into dim_affiliation values (152, "Vitesse");
insert into dim_affiliation values (153, "Vitoria Setubal");
insert into dim_affiliation values (154, "VVVNAVenlo");
insert into dim_affiliation values (155, "VVV-Venlo");
insert into dim_affiliation values (156, "Watford");
insert into dim_affiliation values (157, "Werder Bremen");
insert into dim_affiliation values (158, "West Ham");
insert into dim_affiliation values (159, "Willem II");
insert into dim_affiliation values (160, "Wolves");
insert into dim_affiliation values (161, "Zenit S-Pb");
insert into dim_affiliation values (162, "Zulte Waregem");
